---
- name: Setup php server
  hosts: all
  become: true
  tasks:

  - name: update and upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes


  - name: Install ifconfig
    apt:
       name: net-tools
       state: present

  - name: Set timezone to Africa/Lagos
    timezone:
       name: Africa/Lagos

  - name: Install apache2
    apt:
       name: 
         - apache2
         - libapache2-mod-php
       update_cache: yes
       state: latest

  - name: Start and Enable apache2 Service
    service:
       name: apache2
       state: started
       enabled: true

  - name: host index.php
    shell: echo "<h1>My server name is $(hostname -f)</h1>" > /var/www/html/index.html
  
  - name: restart apache2
    service:
      name: apache2
      state: restarted
