---
- name: Setup php server
  hosts: all
  remote_user: root
  vars: 
    - password: ALTschoolAdMIN007
  tasks:
  - name: Set permissions on Composer
    shell: export COMPOSER_ALLOW_SUPERUSER=1
    args:
      chdir: /var/www/seyiakinnawo 



#Migrate db
  - name: Install Dependencies with Composer
    shell: composer install -n    
    args:  
      chdir: /var/www/seyiakinnawo    



  - name: Create project
    shell: composer create-project -n
    args:
      chdir: /var/www/seyiakinnawo

  
#  - name: Migrate seed
 #   shell: php artisan migrate --seed --force
  #  args:
   #   chdir: /var/www/seyiakinnawo


# enable new site
  - name: Enable new site
    shell: a2dissite 000-default.conf
    notify: Restart Apache

  - name: Enable new site
    shell: a2ensite seyiakinnawo.conf
    notify: Restart Apache

#enable rewrite
  - name: Enable mod rewrite
    shell: a2enmod rewrite
    notify: Reload Apache
  


  - name: update apt
    apt:
      update_cache: yes
      autoclean: yes
      autoremove: yes


#Install and set up ssl certificate
  - name: core
    shell: snap install core


  - name: refresh core
    shell: snap refresh core


  - name: install certbot
    shell: snap install --classic certbot


  - name: configure cerbot to be executable
    shell: ln -s /snap/bin/certbot /usr/bin/certbot
    

  - name: encrypt debian 11
    shell: yes | certbot --apache --agree-tos --redirect -m admin@seyiakinnawo.live -d seyiakinnawo.live -d www.seyiakinnawo.live




  handlers:
  - name: Reload Apache
    service:
      name: apache2
      state: reloaded


  - name: Restart Apache
    service:
      name: apache2
      state: restarted


  - name: Composer migrate seed
    become: true
    become_method: su
    become_user: newUser
    shell: "php artisan migrate --seed"
    args:
      chdir: /var/www/seyiakinnawo
      
